# Generated by Django 2.2.14 on 2020-08-04 18:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for uploaded data set', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Enter name of training data set (e.g. Solar iradiaton data for West Africa)', max_length=200)),
                ('data_file', models.FileField(upload_to='uploads/')),
                ('upload_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['upload_date'],
            },
        ),
    ]
