# Generated by Django 2.2.14 on 2020-08-05 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_trainr', '0002_dataset_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='description',
            field=models.TextField(default='', help_text='Give a brief desccription of data set you are uploading'),
        ),
    ]
