# Generated by Django 2.2.14 on 2020-08-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_trainr', '0003_auto_20200805_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='upload_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
