# Generated by Django 2.2.14 on 2020-08-07 14:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ml_trainr', '0004_auto_20200807_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='upload_date',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
