# Generated by Django 2.2.14 on 2020-08-11 08:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ml_trainr', '0005_auto_20200807_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainedMLModels',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for created ML model', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Enter name of ML model', max_length=200)),
                ('model_file', models.FileField(upload_to='trained_models/')),
                ('description', models.TextField(default='', help_text='Say what the trained ML model does')),
                ('creation_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['creation_date'],
            },
        ),
    ]
